# Thymeleaf設定
spring.thymeleaf.mode=HTML
spring.thymeleaf.check-template-location=false

# PostgreSQL接続設定
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_app
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# ログレベル
logging.level.sample=DEBUG

# セッション有効期限
server.servlet.session.timeout=1d